import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ProductionDepartmentName, SubletQueueItem } from '../types';
import { colors } from '../theme/colors';
import { workflowColors } from '../theme/workflowColors';

type Props = { item: SubletQueueItem | null; recommendedDestination: ProductionDepartmentName | null; destinations: ProductionDepartmentName[]; onSelect: (destination: ProductionDepartmentName) => void; onCancel: () => void };

export function SubletReturnSheet({ item, recommendedDestination, destinations, onSelect, onCancel }: Props) {
  if (!item || !recommendedDestination) return null;
  const previous = item.sublet.productionLocationBeforeSublet;
  const others = destinations.filter((department) => department !== recommendedDestination && department !== previous);
  return <Modal visible transparent animationType="fade" statusBarTranslucent onRequestClose={onCancel}><View style={styles.overlay}><Pressable style={styles.backdrop} onPress={onCancel} /><SafeAreaView style={styles.sheet} edges={['bottom', 'left', 'right']}><View style={styles.handle} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.heading}><View style={styles.headingCopy}><Text style={styles.kicker}>VEHICLE RETURNED</Text><Text style={styles.title}>Where should this vehicle enter production?</Text><Text style={styles.vehicle}>{item.vehicle.make} {item.vehicle.model} · {item.vehicle.stockNumber}</Text></View><Pressable onPress={onCancel} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><Option department={recommendedDestination} label="RECOMMENDED NEXT" detail={`Send to ${recommendedDestination}`} recommended onPress={() => onSelect(recommendedDestination)} />{previous && previous !== recommendedDestination && <Option department={previous} label="PREVIOUS PRODUCTION LOCATION" detail={`Return to ${previous}`} onPress={() => onSelect(previous)} />}<Text style={styles.other}>OTHER DEPARTMENTS</Text>{others.map((department) => <Option key={department} department={department} label={department.toUpperCase()} detail={`Send to ${department}`} onPress={() => onSelect(department)} />)}</ScrollView></SafeAreaView></View></Modal>;
}

function Option({ department, label, detail, recommended = false, onPress }: { department: ProductionDepartmentName; label: string; detail: string; recommended?: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.option, recommended && styles.recommended, { borderLeftColor: workflowColors[department] }, pressed && styles.pressed]}><View style={styles.optionCopy}><Text style={[styles.optionLabel, recommended && styles.recommendedLabel]}>{label}</Text><Text style={styles.detail}>{detail}</Text></View><Text style={[styles.chevron, { color: workflowColors[department] }]}>›</Text></Pressable>; }

const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: 'flex-end' }, backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.68)' }, sheet: { maxHeight: '90%', backgroundColor: colors.panel, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderBottomWidth: 0, borderColor: colors.border }, handle: { width: 42, height: 4, borderRadius: 2, backgroundColor: colors.subtle, alignSelf: 'center', marginTop: 10 }, content: { padding: 20, paddingTop: 14, paddingBottom: 26 }, heading: { flexDirection: 'row', marginBottom: 18 }, headingCopy: { flex: 1 }, kicker: { color: '#C68A43', fontSize: 9, fontWeight: '900', letterSpacing: 1.4 }, title: { color: colors.text, fontSize: 24, lineHeight: 30, fontWeight: '900', marginTop: 6 }, vehicle: { color: colors.muted, fontSize: 11, fontWeight: '800', marginTop: 7 }, close: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.panelRaised }, closeText: { color: colors.muted, fontSize: 29 }, option: { minHeight: 68, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.panelRaised, borderWidth: 1, borderLeftWidth: 5, borderColor: colors.border, borderRadius: 12, paddingHorizontal: 14, marginBottom: 9 }, recommended: { minHeight: 80, backgroundColor: '#2D2418', borderColor: '#A97336' }, optionCopy: { flex: 1 }, optionLabel: { color: colors.text, fontSize: 13, fontWeight: '900' }, recommendedLabel: { color: '#E8B776', fontSize: 15 }, detail: { color: colors.muted, fontSize: 10, fontWeight: '700', marginTop: 4 }, chevron: { fontSize: 28, fontWeight: '800' }, other: { color: colors.subtle, fontSize: 8, fontWeight: '900', letterSpacing: 1.1, marginTop: 10, marginBottom: 8 }, pressed: { opacity: 0.72 } });
