import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ProductionDepartmentName, Vehicle } from '../types';
import { colors } from '../theme/colors';
import { workflowColors } from '../theme/workflowColors';

type Props = { vehicle: Vehicle | null; recommended: ProductionDepartmentName | null; destinations: ProductionDepartmentName[]; onSelect: (destination: ProductionDepartmentName) => void; onCancel: () => void };
export function SubletDenialRoutingSheet({ vehicle, recommended, destinations, onSelect, onCancel }: Props) {
  const request = vehicle?.activeSubletRequest; if (!vehicle || !request || !recommended) return null;
  const previous = request.previousProductionLocation; const others = destinations.filter((item) => item !== recommended && item !== previous);
  return <Modal visible transparent animationType="fade" onRequestClose={onCancel}><View style={styles.overlay}><Pressable style={styles.backdrop} onPress={onCancel} /><SafeAreaView style={styles.sheet} edges={['bottom', 'left', 'right']}><View style={styles.handle} /><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>SUBLET REQUEST DENIED</Text><Text style={styles.title}>Where should this vehicle go now?</Text><Text style={styles.vehicle}>{vehicle.make} {vehicle.model} · {vehicle.stockNumber}</Text><Option department={recommended} label="RECOMMENDED NEXT" onPress={() => onSelect(recommended)} />{previous !== recommended && <Option department={previous} label="PREVIOUS PRODUCTION LOCATION" onPress={() => onSelect(previous)} />}<Text style={styles.other}>OTHER DEPARTMENTS</Text>{others.map((department) => <Option key={department} department={department} label={department.toUpperCase()} onPress={() => onSelect(department)} />)}<Pressable onPress={onCancel} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable></ScrollView></SafeAreaView></View></Modal>;
}
function Option({ department, label, onPress }: { department: ProductionDepartmentName; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.option, { borderLeftColor: workflowColors[department] }]}><View style={styles.copy}><Text style={styles.optionLabel}>{label}</Text><Text style={styles.destination}>Send to {department}</Text></View><Text style={[styles.chevron, { color: workflowColors[department] }]}>›</Text></Pressable>; }
const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: 'flex-end' }, backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.68)' }, sheet: { maxHeight: '88%', backgroundColor: colors.panel, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderBottomWidth: 0, borderColor: colors.border }, handle: { width: 42, height: 4, borderRadius: 2, backgroundColor: colors.subtle, alignSelf: 'center', marginTop: 10 }, content: { padding: 20, paddingTop: 14, paddingBottom: 26 }, kicker: { color: '#D65C63', fontSize: 9, fontWeight: '900', letterSpacing: 1.3 }, title: { color: colors.text, fontSize: 25, lineHeight: 31, fontWeight: '900', marginTop: 6 }, vehicle: { color: colors.muted, fontSize: 11, fontWeight: '800', marginTop: 7, marginBottom: 18 }, option: { minHeight: 70, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.panelRaised, borderWidth: 1, borderLeftWidth: 5, borderColor: colors.border, borderRadius: 12, paddingHorizontal: 14, marginBottom: 9 }, copy: { flex: 1 }, optionLabel: { color: colors.text, fontSize: 13, fontWeight: '900' }, destination: { color: colors.muted, fontSize: 10, marginTop: 4 }, chevron: { fontSize: 28, fontWeight: '800' }, other: { color: colors.subtle, fontSize: 8, fontWeight: '900', letterSpacing: 1.1, marginTop: 10, marginBottom: 8 }, cancel: { minHeight: 54, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 11, marginTop: 8 }, cancelText: { color: colors.text, fontSize: 14, fontWeight: '800' } });
