import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SubletQueueItem } from '../types';
import { colors } from '../theme/colors';
import { BackToFloorButton } from './BackToFloorButton';

type Props = { items: SubletQueueItem[]; onBackToFloor: () => void; onAdvanceStatus: (item: SubletQueueItem) => void };

export function SubletsQueueScreen({ items, onBackToFloor, onAdvanceStatus }: Props) {
  return <View style={styles.page}><BackToFloorButton onPress={onBackToFloor} /><View style={styles.header}><View><Text style={styles.kicker}>EXTERNAL VENDOR WORK</Text><Text style={styles.title}>SUBLETS</Text><Text style={styles.subtitle}>{items.length} active vehicle{items.length === 1 ? '' : 's'}</Text></View><View style={styles.count}><Text style={styles.countText}>{items.length}</Text></View></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.list}>{items.map((item) => <SubletCard key={item.sublet.id} item={item} onAdvance={() => onAdvanceStatus(item)} />)}{items.length === 0 && <View style={styles.empty}><Text style={styles.emptyTitle}>No active Sublets</Text><Text style={styles.emptyText}>External work will appear here.</Text></View>}</ScrollView></View>;
}

function SubletCard({ item, onAdvance }: { item: SubletQueueItem; onAdvance: () => void }) {
  const { vehicle, sublet } = item;
  return <View style={styles.card}><View style={styles.ribbon} /><View style={styles.cardContent}><View style={styles.cardTop}><View style={styles.vehicleCopy}><Text style={styles.vehicle}>{vehicle.year} {vehicle.make} {vehicle.model}</Text><Text style={styles.stock}>{vehicle.stockNumber}</Text></View><View style={styles.status}><Text style={styles.statusText}>{sublet.status.toUpperCase()}</Text></View></View><View style={styles.rule} /><View style={styles.metaRow}><Meta label="CATEGORY" value={sublet.category} /><Meta label="VENDOR" value={sublet.vendorName || 'Not assigned'} /></View><Text style={styles.label}>SERVICE</Text><Text style={styles.service}>{sublet.serviceDescription}</Text><View style={styles.metaRow}><Meta label="EXPECTED RETURN" value={sublet.expectedReturnLabel || 'Not set'} /><Meta label="TIME IN SUBLET" value={elapsed(sublet.createdAt)} /></View>{sublet.productionLocationBeforeSublet && <Text style={styles.previous}>Previous production location · {sublet.productionLocationBeforeSublet}</Text>}<Pressable onPress={onAdvance} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><Text style={styles.actionText}>Vehicle Returned</Text><Text style={styles.chevron}>›</Text></Pressable></View></View>;
}
function Meta({ label, value }: { label: string; value: string }) { return <View style={styles.meta}><Text style={styles.label}>{label}</Text><Text style={styles.metaValue}>{value}</Text></View>; }
function elapsed(createdAt: number) { const minutes = Math.max(0, Math.floor((Date.now() - createdAt) / 60000)); return minutes >= 60 ? `${Math.floor(minutes / 60)} hr ${minutes % 60} min` : `${minutes} min`; }

const styles = StyleSheet.create({
  page: { flex: 1 }, header: { paddingHorizontal: 20, paddingTop: 13, paddingBottom: 10, flexDirection: 'row', alignItems: 'center' }, kicker: { color: '#C68A43', fontSize: 9, fontWeight: '900', letterSpacing: 1.4 }, title: { color: colors.text, fontSize: 32, fontWeight: '900', marginTop: 3 }, subtitle: { color: colors.muted, fontSize: 11, marginTop: 2 }, count: { marginLeft: 'auto', minWidth: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#3B2B19' }, countText: { color: '#E2A55F', fontSize: 14, fontWeight: '900' }, list: { paddingHorizontal: 20, paddingBottom: 42 }, card: { flexDirection: 'row', backgroundColor: colors.panelRaised, borderWidth: 1, borderColor: colors.border, borderRadius: 14, overflow: 'hidden', marginBottom: 14 }, ribbon: { width: 6, backgroundColor: '#B87834' }, cardContent: { flex: 1, padding: 16 }, cardTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 }, vehicleCopy: { flex: 1 }, vehicle: { color: colors.text, fontSize: 18, fontWeight: '900' }, stock: { color: colors.muted, fontSize: 10, fontWeight: '800', marginTop: 4 }, status: { backgroundColor: '#332819', borderRadius: 7, paddingHorizontal: 8, paddingVertical: 6 }, statusText: { color: '#E2A55F', fontSize: 8, fontWeight: '900' }, rule: { height: 1, backgroundColor: colors.border, marginVertical: 13 }, metaRow: { flexDirection: 'row', gap: 16, marginTop: 11 }, meta: { flex: 1 }, label: { color: colors.subtle, fontSize: 8, fontWeight: '900', letterSpacing: 1, marginBottom: 4 }, metaValue: { color: '#D6DADE', fontSize: 11, lineHeight: 15, fontWeight: '800' }, service: { color: '#D6DADE', fontSize: 13, lineHeight: 18, fontWeight: '800' }, previous: { color: colors.subtle, fontSize: 9, fontWeight: '700', marginTop: 12 }, action: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#B87834', borderRadius: 11, marginTop: 15 }, actionText: { color: '#0B0E12', fontSize: 14, fontWeight: '900' }, chevron: { position: 'absolute', right: 15, color: '#0B0E12', fontSize: 25 }, empty: { alignItems: 'center', paddingTop: 50 }, emptyTitle: { color: colors.text, fontSize: 17, fontWeight: '900' }, emptyText: { color: colors.muted, fontSize: 12, marginTop: 6 }, pressed: { opacity: 0.72 },
});
